version: '3.9'
services:
  db:
    image: mysql
    container_name: practicdb
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: 'igeargeekpracticdb'

  api:
    image: golang-api
    container_name: "practicapi"
    depends_on:
      - db
    build: .
    ports:
      - "8000:8000"
    expose:
      - 8000
    environment:
      DB_ADDR: "root:admin@tcp(host.docker.internal:3306)/igeargeekpracticdb?charset=utf8mb4&parseTime=True&loc=Local" 
      JWT_SECRET_KEY: "igeargeekjiw" 
      PORT: "8000"
    command: "go run main.go"

  # app:
  #   image: webapp
  #   container_name: "nuxt-app"
  #   depends_on:
  #     - api
  #     - db
  #   build: ../frontend/
  #   ports:
  #     - "3000:3000"
  #   expose: 
  #     - 3000
  #   command: "npm run dev"